### ISSUE TITLE
Some environment problems I met

### ISSUE THREAD

**Issue by yuanze1024** [TEXTurePaper/TEXTurePaper#22]
I have met some problems and I'm going to record it in case someone else may have the same peoblem.

1. kaolin: CUDA error: no kernel image is available for execution on the device
**NOTICE: The steps downward, work only if the exception is thrown by the kaolin.**
You can try to reinstall the kaolin (if you installed kaolin using its precompiled package) by compiling it yourself.
For me, kaolin 0.11.0, pytorch 1.13.0 and cuda 11.6 work.
2. TypeError: write() got an unexpected keyword argument 'fps'
Try this.
https://github.com/OpenTalker/SadTalker/issues/276#issuecomment-1570190070

-----
I don't know if I should submit an issue because the code is running well.

**Comment by iyuner** [comment]
I think it's the kaolin version problem firstly, related issues you can check: https://github.com/TEXTurePaper/TEXTurePaper/issues/1

1. When I tried to install kaolin 0.11.0, there is no version, error here:
```
Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
ERROR: Could not find a version that satisfies the requirement kaolin==0.11 (from versions: 0.1, 0.12.0, 0.13.0, 0.14.0)
ERROR: No matching distribution found for kaolin==0.11
```
2. Then I tried kaolin 0.12.0 the error is: `CUDA error: no kernel image is available for execution on the device`. So kaolin version need be the updated, I used 0.14.0 by running
```
pip install kaolin -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
```

---

Here are my setup steps:
1. `git clone xxx` and `conda create -n py38 python=3.8`
2. `cd xx & pip install -r requirement.txt`
3. `pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113`
4. `pip install kaolin -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html`
Then it works.
